FROM ubuntu:14.04
MAINTAINER prabuddha <prabuddha.nike13@gmail.com>

RUN echo mysql-server mysql-server/root_password password root123456 | debconf-set-selections
RUN echo mysql-server mysql-server/root_password_again password root123456 | debconf-set-selections


RUN echo "[client]" >> ~/.my.cnf
RUN echo "user = root" >> ~/.my.cnf
RUN echo "password = root123456" >> ~/.my.cnf
# Install MariaDB.
RUN \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server && \
  rm -rf /var/lib/apt/lists/* && \
  sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/my.cnf && \
  echo "mysqld_safe &" > /tmp/config && \
  echo "mysqladmin --silent --wait=30 ping || exit 1" >> /tmp/config && \
  echo "mysql -e 'GRANT ALL PRIVILEGES ON *.* TO \"root\"@\"%\" IDENTIFIED BY \"root123456\" WITH GRANT OPTION;'" >> /tmp/config && \
  bash /tmp/config && \
  rm -f /tmp/config

# Define default command.
CMD ["mysqld_safe"]

# Expose ports.
EXPOSE 3306
